version: '3'
services:
  # frontend:
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  backend:
    build: ./todo-app/back-end
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001
  # tests:
  #   ports:
  #     - 3000:3000
  